//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.invHServ.Api.Models.Ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Center()
        {
            this.InvDtlData = new HashSet<InvDtlData>();
            this.InvDtlData1 = new HashSet<InvDtlData>();
            this.InvDtlData2 = new HashSet<InvDtlData>();
            this.InvDtlData3 = new HashSet<InvDtlData>();
            this.InvDtlData4 = new HashSet<InvDtlData>();
            this.ItemData = new HashSet<ItemData>();
            this.ItemData1 = new HashSet<ItemData>();
            this.ItemData2 = new HashSet<ItemData>();
            this.InvOrdr = new HashSet<InvOrdr>();
            this.Store = new HashSet<Store>();
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int Center1 { get; set; }
        public Nullable<short> CenterGrp { get; set; }
        public string CenterDsc { get; set; }
        public string CenterLtnDsc { get; set; }
        public string Equal_code { get; set; }
        public Nullable<byte> ActvFlg { get; set; }
        public Nullable<int> CostCenter1 { get; set; }
        public Nullable<int> CostCenter2 { get; set; }
        public Nullable<int> CostCenter3 { get; set; }
        public string CrnEf { get; set; }
        public string UnqDsc { get; set; }
        public Nullable<byte> IsStoreAmt { get; set; }
        public Nullable<byte> Detail { get; set; }
        public Nullable<int> RefCenter { get; set; }
        public Nullable<int> MultyMediaDoc { get; set; }
        public string MultyMediaDocX { get; set; }
        public string branch_filter_spec { get; set; }
        public string C_branch_filter_spec { get; set; }
        public Nullable<int> CntrSpec1 { get; set; }
        public Nullable<int> CntrSpec2 { get; set; }
        public Nullable<int> CntrSpec3 { get; set; }
        public Nullable<int> CntrSpec4 { get; set; }
        public Nullable<int> CntrSpec5 { get; set; }
        public Nullable<int> CntrSpec6 { get; set; }
        public Nullable<int> CntrSpec7 { get; set; }
        public Nullable<int> CntrSpec8 { get; set; }
        public System.Guid RowGUID { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual CenterGrp CenterGrp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlData1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlData2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlData3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlData4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemData> ItemData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemData> ItemData1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemData> ItemData2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvOrdr> InvOrdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}
