//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.invHServ.Api.Models.Ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Func
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Func()
        {
            this.UserDomain = new HashSet<UserDomain>();
        }
    
        public string RaySys { get; set; }
        public string Func1 { get; set; }
        public string FuncDsc { get; set; }
        public string FuncLtnDsc { get; set; }
        public string MainFunc { get; set; }
        public Nullable<int> Srt { get; set; }
        public Nullable<byte> AnyBranch { get; set; }
        public string ProjectTyp { get; set; }
        public Nullable<byte> FuncStat { get; set; }
        public string FuncAct { get; set; }
        public string ShortcutKey { get; set; }
        public Nullable<byte> ToolbarSort { get; set; }
        public Nullable<byte> HasSeparator { get; set; }
        public Nullable<byte> UsrAdd { get; set; }
        public string FuncIconKey { get; set; }
        public string MRSFunc { get; set; }
        public string OldFunc { get; set; }
        public string ToolBarProjectTyp { get; set; }
        public string ToolBarDsc { get; set; }
        public string ToolBarLtnDsc { get; set; }
        public string WebFuncAct { get; set; }
        public System.Guid RowGUID { get; set; }
        public byte[] RowVersion { get; set; }
        public string MRSFuncRaySys { get; set; }
    
        public virtual RaySys RaySys1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDomain> UserDomain { get; set; }
    }
}
