//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.invHServ.Api.Models.Ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDocTyp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvDocTyp()
        {
            this.InvHdrData = new HashSet<InvHdrData>();
            this.InvDtlData = new HashSet<InvDtlData>();
            this.InvRfDoc = new HashSet<InvRfDoc>();
        }
    
        public byte DocType { get; set; }
        public string DocTypeDesc { get; set; }
        public string DescShop { get; set; }
        public short SeqDocType { get; set; }
        public Nullable<byte> CatgType { get; set; }
        public Nullable<byte> IsDocOpn { get; set; }
        public Nullable<byte> OpnRcptPriceTyp { get; set; }
        public string VbFormName { get; set; }
        public string VbDescFrmName { get; set; }
        public Nullable<byte> AudtDocType { get; set; }
        public Nullable<byte> IsAuditDoc { get; set; }
        public Nullable<short> TabNo { get; set; }
        public Nullable<byte> RefDoc { get; set; }
        public Nullable<byte> RefDocNo { get; set; }
        public Nullable<byte> MoveDoc { get; set; }
        public Nullable<byte> SerailAcc { get; set; }
        public Nullable<byte> SortInEdGrp { get; set; }
        public Nullable<byte> IsShop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvHdrData> InvHdrData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRfDoc> InvRfDoc { get; set; }
    }
}
