//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.invHServ.Api.Models.Ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvRfDoc
    {
        public int FiscalYear { get; set; }
        public string StoreNo { get; set; }
        public byte DocType { get; set; }
        public int DocNo { get; set; }
        public short CountNo { get; set; }
        public string DestStoreNo { get; set; }
        public Nullable<byte> DocEntStatus { get; set; }
        public short DocRow { get; set; }
        public Nullable<byte> LnkType { get; set; }
        public int RefFiscalYear { get; set; }
        public string RefStore { get; set; }
        public byte RefDocType { get; set; }
        public int RefDocNo { get; set; }
        public short RefDocRow { get; set; }
        public string PartNo { get; set; }
        public string RefDestStoreNo { get; set; }
        public Nullable<byte> RefEntDocStatus { get; set; }
        public Nullable<decimal> RefQty { get; set; }
        public string RefPArtNo { get; set; }
        public string RefBinNo { get; set; }
    
        public virtual InvDocTyp InvDocTyp { get; set; }
        public virtual InvDtlData InvDtlData { get; set; }
        public virtual InvPrd InvPrd { get; set; }
        public virtual ItemData ItemData { get; set; }
        public virtual ItemData ItemData1 { get; set; }
        public virtual Store Store { get; set; }
    }
}
