//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.invHServ.Api.Models.Ray
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RayvarzEntities : DbContext
    {
        public RayvarzEntities()
            : base("name=RayvarzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Center> Center { get; set; }
        public virtual DbSet<CenterGrp> CenterGrp { get; set; }
        public virtual DbSet<InvDocTyp> InvDocTyp { get; set; }
        public virtual DbSet<InvDtlData> InvDtlData { get; set; }
        public virtual DbSet<InvHdrData> InvHdrData { get; set; }
        public virtual DbSet<InvMstr> InvMstr { get; set; }
        public virtual DbSet<ItemData> ItemData { get; set; }
        public virtual DbSet<Func> Func { get; set; }
        public virtual DbSet<InvOrdr> InvOrdr { get; set; }
        public virtual DbSet<InvPrd> InvPrd { get; set; }
        public virtual DbSet<RaySys> RaySys { get; set; }
        public virtual DbSet<RaySysSpc> RaySysSpc { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<UserDomain> UserDomain { get; set; }
        public virtual DbSet<UserId> UserId { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<InvRfDoc> InvRfDoc { get; set; }
    }
}
