//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.invHServ.Api.Models.Ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaySysSpc
    {
        public string RaySys { get; set; }
        public string InfTit { get; set; }
        public string InfDsc { get; set; }
        public string InfVal { get; set; }
        public byte[] InfImage { get; set; }
        public System.Guid RowGUID { get; set; }
        public byte[] RowVersion { get; set; }
        public string InfDscLatin { get; set; }
        public Nullable<byte> ShowAsParameter { get; set; }
        public string SystemVisibility { get; set; }
    
        public virtual RaySys RaySys1 { get; set; }
    }
}
