//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.invHServ.Api.Models.Ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaySys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RaySys()
        {
            this.Func = new HashSet<Func>();
            this.RaySys11 = new HashSet<RaySys>();
            this.RaySysSpc = new HashSet<RaySysSpc>();
            this.UserDomain = new HashSet<UserDomain>();
        }
    
        public string RaySys1 { get; set; }
        public string SysDsc { get; set; }
        public string SysLtnDsc { get; set; }
        public string Domain { get; set; }
        public System.Guid RowGUID { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Func> Func { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaySys> RaySys11 { get; set; }
        public virtual RaySys RaySys2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaySysSpc> RaySysSpc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDomain> UserDomain { get; set; }
    }
}
