//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.UserDomains = new HashSet<UserDomain>();
        }
    
        public int Branch1 { get; set; }
        public string BranchDsc { get; set; }
        public string BranchLDsc { get; set; }
        public Nullable<byte> IsCenter { get; set; }
        public string DBName { get; set; }
        public string PayCrnDat { get; set; }
        public Nullable<int> DBBranch { get; set; }
        public Nullable<byte> AstAccSerial { get; set; }
        public Nullable<decimal> AstFrOwner { get; set; }
        public Nullable<decimal> AstToOwner { get; set; }
        public Nullable<decimal> AstFrCenter { get; set; }
        public Nullable<decimal> AstToCenter { get; set; }
        public Nullable<int> AstFrSettlement { get; set; }
        public Nullable<int> AstToSettlement { get; set; }
        public Nullable<int> AstFrCenter2 { get; set; }
        public Nullable<int> AstToCenter2 { get; set; }
        public Nullable<int> AstFrCenter3 { get; set; }
        public Nullable<int> AstToCenter3 { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public string NationalCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDomain> UserDomains { get; set; }
    }
}
