//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterGrp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CenterGrp()
        {
            this.Centers = new HashSet<Center>();
        }
    
        public short CenterGrp1 { get; set; }
        public string CenterGrpDsc { get; set; }
        public string CenterGrpLtnDsc { get; set; }
        public Nullable<int> OpnCenter { get; set; }
        public string RefTbl { get; set; }
        public string branch_filter_spec { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<byte> Person { get; set; }
        public string CenterGrpShortDsc { get; set; }
        public string CenterGrpShortLtnDsc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Center> Centers { get; set; }
    }
}
