//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Center()
        {
            this.Center11 = new HashSet<Center>();
            this.InvDtlDatas = new HashSet<InvDtlData>();
            this.InvDocs = new HashSet<InvDoc>();
            this.InvDocs1 = new HashSet<InvDoc>();
            this.InvDtlDatas1 = new HashSet<InvDtlData>();
            this.InvDtlDatas2 = new HashSet<InvDtlData>();
            this.InvDtlDatas3 = new HashSet<InvDtlData>();
            this.InvDtlDatas4 = new HashSet<InvDtlData>();
            this.InvOrdrs = new HashSet<InvOrdr>();
            this.ItemDatas = new HashSet<ItemData>();
            this.ItemDatas1 = new HashSet<ItemData>();
            this.ItemDatas2 = new HashSet<ItemData>();
            this.Stores = new HashSet<Store>();
            this.Suppliers = new HashSet<Supplier>();
            this.Suppliers1 = new HashSet<Supplier>();
            this.Suppliers2 = new HashSet<Supplier>();
            this.Suppliers3 = new HashSet<Supplier>();
        }
    
        public int Center1 { get; set; }
        public Nullable<short> CenterGrp { get; set; }
        public string CenterDsc { get; set; }
        public string CenterLtnDsc { get; set; }
        public string Equal_code { get; set; }
        public Nullable<byte> ActvFlg { get; set; }
        public Nullable<int> CostCenter1 { get; set; }
        public Nullable<int> CostCenter2 { get; set; }
        public Nullable<int> CostCenter3 { get; set; }
        public string CrnEf { get; set; }
        public string UnqDsc { get; set; }
        public Nullable<byte> IsStoreAmt { get; set; }
        public Nullable<byte> Detail { get; set; }
        public Nullable<int> RefCenter { get; set; }
        public Nullable<int> MultyMediaDoc { get; set; }
        public string MultyMediaDocX { get; set; }
        public string branch_filter_spec { get; set; }
        public string C_branch_filter_spec { get; set; }
        public Nullable<int> CntrSpec1 { get; set; }
        public Nullable<int> CntrSpec2 { get; set; }
        public Nullable<int> CntrSpec3 { get; set; }
        public Nullable<int> CntrSpec4 { get; set; }
        public Nullable<int> CntrSpec5 { get; set; }
        public Nullable<int> CntrSpec6 { get; set; }
        public Nullable<int> CntrSpec7 { get; set; }
        public Nullable<int> CntrSpec8 { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public string NationalCode { get; set; }
        public Nullable<byte> NonIsuueOpening { get; set; }
        public Nullable<int> AlternativeCenter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Center> Center11 { get; set; }
        public virtual Center Center2 { get; set; }
        public virtual CenterGrp CenterGrp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDoc> InvDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDoc> InvDocs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvOrdr> InvOrdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemData> ItemDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemData> ItemDatas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemData> ItemDatas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers3 { get; set; }
    }
}
