//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAddDocInf
    {
        public int FiscalYear { get; set; }
        public string StoreNo { get; set; }
        public byte DocType { get; set; }
        public int DocNo { get; set; }
        public string DestStoreNo { get; set; }
        public Nullable<short> StkCountNo { get; set; }
        public short CountNo { get; set; }
        public Nullable<byte> DocEntStatus { get; set; }
        public short DocRow { get; set; }
        public short FldCod { get; set; }
        public string CompData { get; set; }
        public Nullable<decimal> CompNum { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual InvDtlData InvDtlData { get; set; }
        public virtual InvDocTyp InvDocTyp { get; set; }
        public virtual InvPrd InvPrd { get; set; }
        public virtual Store Store { get; set; }
    }
}
