//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvArcSoh
    {
        public int FiscalYear { get; set; }
        public string StoreNo { get; set; }
        public string PartNo { get; set; }
        public string DocDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual ItemData ItemData { get; set; }
        public virtual InvPrd InvPrd { get; set; }
        public virtual Store Store { get; set; }
    }
}
