//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAssistantVw_getPartGrpFullPath
    {
        public string PartGrp { get; set; }
        public string PartGrpDsc { get; set; }
        public string PrntPartGrp { get; set; }
        public string FullPath { get; set; }
    }
}
