//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDoc
    {
        public string RaySys { get; set; }
        public int FiscalYear { get; set; }
        public string StoreNo { get; set; }
        public byte DocType { get; set; }
        public int DocNo { get; set; }
        public short DocRow { get; set; }
        public string PartNo { get; set; }
        public string Serial { get; set; }
        public Nullable<int> Center { get; set; }
        public string DocDate { get; set; }
        public string UntCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<int> ConsType { get; set; }
        public Nullable<int> RcptType { get; set; }
        public Nullable<byte> ReqType { get; set; }
        public Nullable<byte> RtrnStrReason { get; set; }
        public Nullable<byte> RtrnBuyReason { get; set; }
        public Nullable<int> ReqCenter { get; set; }
        public string Supplier { get; set; }
        public Nullable<long> OrderNo { get; set; }
        public string BinNo { get; set; }
        public Nullable<int> RegNo { get; set; }
        public string LcNo { get; set; }
        public string NeedDate { get; set; }
        public Nullable<short> RunNo { get; set; }
        public Nullable<byte> Flag { get; set; }
        public Nullable<int> Error { get; set; }
        public Nullable<int> InvRfDocNo { get; set; }
        public Nullable<short> InvRfDocRow { get; set; }
        public Nullable<decimal> RefConsQty { get; set; }
        public string Cstmr { get; set; }
        public Nullable<int> InvRfFiscalYear { get; set; }
        public Nullable<byte> SetVoid { get; set; }
        public string SalePartNo { get; set; }
        public Nullable<decimal> SaleQty { get; set; }
        public Nullable<short> SaleRow { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public string DocDsc { get; set; }
    
        public virtual Center Center1 { get; set; }
        public virtual Center Center2 { get; set; }
        public virtual InvCnsTyp InvCnsTyp { get; set; }
        public virtual InvDocTyp InvDocTyp { get; set; }
        public virtual RaySy RaySy { get; set; }
        public virtual InvRcptTyp InvRcptTyp { get; set; }
        public virtual InvReqTyp InvReqTyp { get; set; }
        public virtual InvRtrnBuy InvRtrnBuy { get; set; }
        public virtual InvRtrnStr InvRtrnStr { get; set; }
        public virtual ItemData ItemData { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ItemData ItemData1 { get; set; }
    }
}
