//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDtlData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvDtlData()
        {
            this.InvAddDocInfs = new HashSet<InvAddDocInf>();
            this.InvRfDocs = new HashSet<InvRfDoc>();
        }
    
        public int FiscalYear { get; set; }
        public string StoreNo { get; set; }
        public byte DocType { get; set; }
        public int DocNo { get; set; }
        public string DestStoreNo { get; set; }
        public Nullable<short> StkCountNo { get; set; }
        public short CountNo { get; set; }
        public Nullable<byte> DocEntStatus { get; set; }
        public short DocRow { get; set; }
        public string PartNo { get; set; }
        public string Serial { get; set; }
        public Nullable<int> Center { get; set; }
        public string DocDate { get; set; }
        public string UntCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> AudtQty { get; set; }
        public Nullable<decimal> RefConsQty { get; set; }
        public Nullable<decimal> RefOrder { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> CompAmt { get; set; }
        public Nullable<decimal> AudtAmt { get; set; }
        public Nullable<int> ConsType { get; set; }
        public Nullable<int> RcptType { get; set; }
        public Nullable<byte> ReqType { get; set; }
        public Nullable<byte> RtrnStrReason { get; set; }
        public Nullable<byte> RtrnBuyReason { get; set; }
        public Nullable<int> ReqCenter { get; set; }
        public string Supplier { get; set; }
        public Nullable<long> OrderNo { get; set; }
        public string BinNo { get; set; }
        public Nullable<int> RegNo { get; set; }
        public string LcNo { get; set; }
        public string NeedDate { get; set; }
        public Nullable<byte> AudtReason { get; set; }
        public string PrcDate { get; set; }
        public Nullable<short> PrcSeqDoc { get; set; }
        public Nullable<byte> RefStatus { get; set; }
        public Nullable<short> DetValSeq { get; set; }
        public Nullable<short> AccDocSeq { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> RtnQty { get; set; }
        public Nullable<int> RfDocNo { get; set; }
        public Nullable<short> RfDocRow { get; set; }
        public string AccDocNo { get; set; }
        public Nullable<byte> SetPrice { get; set; }
        public Nullable<int> UpdTime { get; set; }
        public Nullable<byte> SetVoid { get; set; }
        public Nullable<byte> IsNewYear { get; set; }
        public string FactorNo { get; set; }
        public string SalePartNo { get; set; }
        public Nullable<decimal> SaleQty { get; set; }
        public Nullable<short> SaleRow { get; set; }
        public string TraceKey { get; set; }
        public Nullable<decimal> StoreAmt { get; set; }
        public Nullable<int> Act3 { get; set; }
        public Nullable<decimal> TollAmt { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public string DocDsc { get; set; }
        public string FactorDate { get; set; }
        public string TreatyNo { get; set; }
        public Nullable<short> OldRow { get; set; }
        public Nullable<int> GdiRefDocNo { get; set; }
        public Nullable<short> GdiRefDocRow { get; set; }
        public string GdiRefPartNo { get; set; }
        public string GdiRefStore { get; set; }
        public string FromPlaque { get; set; }
        public string ToPlaque { get; set; }
        public Nullable<decimal> CntQty { get; set; }
        public string OrgPelakNo { get; set; }
        public string FlwCode { get; set; }
        public Nullable<int> DespositRng { get; set; }
        public string MeetingDate { get; set; }
        public Nullable<int> Act4 { get; set; }
        public Nullable<int> Act5 { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public string MultyMediaDocX { get; set; }
        public Nullable<int> MultyMediaDoc { get; set; }
        public string CrdtId { get; set; }
    
        public virtual Center Center1 { get; set; }
        public virtual Center Center2 { get; set; }
        public virtual Center Center3 { get; set; }
        public virtual Center Center4 { get; set; }
        public virtual Center Center5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvAddDocInf> InvAddDocInfs { get; set; }
        public virtual InvCnsTyp InvCnsTyp { get; set; }
        public virtual InvDocTyp InvDocTyp { get; set; }
        public virtual InvHdrData InvHdrData { get; set; }
        public virtual ItemData ItemData { get; set; }
        public virtual InvOrdr InvOrdr { get; set; }
        public virtual InvRcptTyp InvRcptTyp { get; set; }
        public virtual InvReqTyp InvReqTyp { get; set; }
        public virtual InvRtrnBuy InvRtrnBuy { get; set; }
        public virtual InvRtrnStr InvRtrnStr { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRfDoc> InvRfDocs { get; set; }
        public virtual InvPrd InvPrd { get; set; }
        public virtual Store Store { get; set; }
    }
}
