//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvOrdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvOrdr()
        {
            this.InvDtlDatas = new HashSet<InvDtlData>();
            this.InvSerials = new HashSet<InvSerial>();
        }
    
        public long OrdrNO { get; set; }
        public string Cstmr { get; set; }
        public string OrdrDsc { get; set; }
        public string PartNo { get; set; }
        public Nullable<decimal> Stqty { get; set; }
        public Nullable<int> Center { get; set; }
        public Nullable<byte> Active { get; set; }
        public string ManufacturingDate { get; set; }
        public string ExpirationDate { get; set; }
        public string RetestDate { get; set; }
        public string PrdSerial { get; set; }
        public Nullable<double> FillingWeight { get; set; }
        public string PrdBgnProj { get; set; }
        public string OrderNoEq { get; set; }
        public string branch_filter_spec { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public string OrdrLtnDsc { get; set; }
    
        public virtual Center Center1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas { get; set; }
        public virtual ItemData ItemData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvSerial> InvSerials { get; set; }
    }
}
