//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPrd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvPrd()
        {
            this.InvHdrDatas = new HashSet<InvHdrData>();
            this.InvAddDocInfs = new HashSet<InvAddDocInf>();
            this.InvAddDocInfHdrs = new HashSet<InvAddDocInfHdr>();
            this.InvArcSohs = new HashSet<InvArcSoh>();
            this.InvDtlDatas = new HashSet<InvDtlData>();
            this.InvMstrs = new HashSet<InvMstr>();
            this.InvSerials = new HashSet<InvSerial>();
            this.InvRfDocs = new HashSet<InvRfDoc>();
        }
    
        public int FiscalYear { get; set; }
        public string StartFiscalYear { get; set; }
        public string EndFiscalYear { get; set; }
        public Nullable<byte> FiscalStatus { get; set; }
        public Nullable<byte> IsMoveAMT { get; set; }
        public Nullable<byte> IsMoveRemainQty { get; set; }
        public Nullable<byte> IsSixteenMonth { get; set; }
        public string EndSixteenMonthYear { get; set; }
        public Nullable<byte> IsMovePermanently { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvHdrData> InvHdrDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvAddDocInf> InvAddDocInfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvAddDocInfHdr> InvAddDocInfHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvArcSoh> InvArcSohs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMstr> InvMstrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvSerial> InvSerials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRfDoc> InvRfDocs { get; set; }
    }
}
