//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvSerial
    {
        public string StoreNo { get; set; }
        public string PartNo { get; set; }
        public string Serail { get; set; }
        public Nullable<decimal> Soh { get; set; }
        public Nullable<decimal> TotRcpt { get; set; }
        public Nullable<decimal> TotIssu { get; set; }
        public string ExpDate { get; set; }
        public string Seri { get; set; }
        public int FiscalYear { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Potention { get; set; }
        public string OptmIsuDat { get; set; }
        public string QcNo { get; set; }
        public Nullable<byte> ConsSt { get; set; }
        public Nullable<byte> ValidExit { get; set; }
        public string ConfirmDate { get; set; }
        public Nullable<int> TagNo { get; set; }
        public Nullable<byte> Colour { get; set; }
        public string Cstmr { get; set; }
        public string MotorNo { get; set; }
        public string ChassisNo { get; set; }
        public string Supplier { get; set; }
        public Nullable<short> TrnsPkgTyp { get; set; }
        public string SuppSerial { get; set; }
        public Nullable<short> PackCount { get; set; }
        public Nullable<int> IssueNo { get; set; }
        public string SuppExpDate { get; set; }
        public string SuppEntrDate { get; set; }
        public string Binno { get; set; }
        public Nullable<int> MultyMediaDoc { get; set; }
        public string MultyMediaDocX { get; set; }
        public Nullable<long> OrdrNO { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual InvModel InvModel { get; set; }
        public virtual InvOrdr InvOrdr { get; set; }
        public virtual InvPrd InvPrd { get; set; }
        public virtual ItemData ItemData { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier1 { get; set; }
    }
}
