//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemData()
        {
            this.InvArcSohs = new HashSet<InvArcSoh>();
            this.InvDocs = new HashSet<InvDoc>();
            this.InvDocs1 = new HashSet<InvDoc>();
            this.InvDtlDatas = new HashSet<InvDtlData>();
            this.InvMstrs = new HashSet<InvMstr>();
            this.InvOrdrs = new HashSet<InvOrdr>();
            this.InvRfDocs = new HashSet<InvRfDoc>();
            this.InvRfDocs1 = new HashSet<InvRfDoc>();
            this.InvSerials = new HashSet<InvSerial>();
        }
    
        public string PartNo { get; set; }
        public string PartNoDsc { get; set; }
        public string PartLtnDsc { get; set; }
        public string TechnicalNo { get; set; }
        public string PartPrvNo { get; set; }
        public string PartGrp { get; set; }
        public string PrdPartGrp { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> InvDefCenter { get; set; }
        public Nullable<int> Center { get; set; }
        public string UntCode { get; set; }
        public string TtlUntCode { get; set; }
        public string TtlUnt { get; set; }
        public string PrtnUnt { get; set; }
        public string OrdrUnt { get; set; }
        public string BomUnt { get; set; }
        public Nullable<double> ExchngTtlToInv { get; set; }
        public Nullable<double> ExchngPrtnToInv { get; set; }
        public Nullable<double> ExchngTtlToPrtn { get; set; }
        public Nullable<double> ExchngOrdrToInv { get; set; }
        public Nullable<decimal> ExchngBomToInv { get; set; }
        public Nullable<decimal> ExchangeTtlUntToUnt { get; set; }
        public Nullable<decimal> ExchngSaleToDis { get; set; }
        public Nullable<int> RcptType { get; set; }
        public Nullable<int> ConsType { get; set; }
        public string MapNo { get; set; }
        public Nullable<short> KeepType { get; set; }
        public Nullable<byte> ImpType { get; set; }
        public Nullable<byte> UsedCode { get; set; }
        public Nullable<short> ProdType { get; set; }
        public Nullable<byte> TransportType { get; set; }
        public Nullable<short> TrnsPkgTyp { get; set; }
        public Nullable<decimal> PureWght { get; set; }
        public Nullable<decimal> UnpureWght { get; set; }
        public Nullable<decimal> BoxWght { get; set; }
        public string WghtUnt { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string LenUnt { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string WidthUnt { get; set; }
        public Nullable<decimal> High { get; set; }
        public string HighUnt { get; set; }
        public Nullable<int> MultyMediaDoc { get; set; }
        public string MultyMediaDocX { get; set; }
        public Nullable<byte> OrderMetType { get; set; }
        public Nullable<decimal> ToolRate { get; set; }
        public Nullable<short> TimeOfProcure { get; set; }
        public Nullable<short> SpanTime { get; set; }
        public Nullable<decimal> MinOrderPoint { get; set; }
        public Nullable<decimal> AvgMonCons { get; set; }
        public Nullable<decimal> SafetyStock { get; set; }
        public Nullable<decimal> OrderPoint { get; set; }
        public Nullable<decimal> OptmOrdQty { get; set; }
        public Nullable<short> LeadTime { get; set; }
        public Nullable<byte> IsPrdBatch { get; set; }
        public Nullable<short> ExpDue { get; set; }
        public string PartSpecId1 { get; set; }
        public string PartSpecId2 { get; set; }
        public string PartSpecId3 { get; set; }
        public string PartSpecId4 { get; set; }
        public Nullable<short> PartAdjTyp1 { get; set; }
        public Nullable<short> PartAdjTyp2 { get; set; }
        public Nullable<short> PartAdjTyp3 { get; set; }
        public Nullable<short> PartAdjTyp4 { get; set; }
        public Nullable<byte> Salable { get; set; }
        public Nullable<byte> IsMakePart { get; set; }
        public Nullable<byte> IsMtrl { get; set; }
        public Nullable<byte> IsMchnPart { get; set; }
        public Nullable<byte> IsTools { get; set; }
        public Nullable<byte> IsAsset { get; set; }
        public Nullable<byte> IsMold { get; set; }
        public Nullable<byte> ISOfsTool { get; set; }
        public Nullable<byte> IsConsTool { get; set; }
        public Nullable<byte> IsFccPart { get; set; }
        public Nullable<long> OrdrNo { get; set; }
        public Nullable<byte> NotActiv { get; set; }
        public Nullable<byte> IsCut { get; set; }
        public Nullable<decimal> DisMinReq { get; set; }
        public Nullable<decimal> MinFeed { get; set; }
        public Nullable<decimal> MaxFeed { get; set; }
        public string CreateDate { get; set; }
        public Nullable<decimal> AmtPtn { get; set; }
        public Nullable<decimal> DisPrdPercent { get; set; }
        public Nullable<decimal> PurityDegree { get; set; }
        public Nullable<decimal> PurityDegreeRatio { get; set; }
        public Nullable<byte> IsFeed { get; set; }
        public Nullable<decimal> OlympPrice { get; set; }
        public Nullable<byte> IsExpired { get; set; }
        public Nullable<short> CostAccType { get; set; }
        public Nullable<decimal> SaleRsv { get; set; }
        public Nullable<short> PrdPartType { get; set; }
        public Nullable<int> ExpiredDuration { get; set; }
        public Nullable<bool> IsSCMMaterial { get; set; }
        public Nullable<decimal> WUPkgTyp { get; set; }
        public Nullable<decimal> IncDeliver { get; set; }
        public Nullable<byte> IsPrdPart { get; set; }
        public string UnqDsc { get; set; }
        public Nullable<decimal> Sarakperc { get; set; }
        public Nullable<decimal> StorePerc { get; set; }
        public Nullable<decimal> StoreAmt { get; set; }
        public string LastChngDate { get; set; }
        public string NationalPartCod { get; set; }
        public Nullable<int> Act3 { get; set; }
        public Nullable<decimal> PurityDegreePharmacy { get; set; }
        public string CostomsNo { get; set; }
        public string PartComent { get; set; }
        public string ItemCode { get; set; }
        public string branch_filter_spec { get; set; }
        public Nullable<int> AstCoClassify { get; set; }
        public string AstDpType { get; set; }
        public Nullable<int> AstUsedTime { get; set; }
        public Nullable<decimal> AstDpRate { get; set; }
        public Nullable<byte> AstUnt { get; set; }
        public string C_branch_filter_spec { get; set; }
        public Nullable<byte> IsPack { get; set; }
        public Nullable<byte> IsShop { get; set; }
        public Nullable<int> Categorize { get; set; }
        public Nullable<byte> IsLabTools { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<byte> SeasonalTradePartType { get; set; }
    
        public virtual Center Center1 { get; set; }
        public virtual Center Center2 { get; set; }
        public virtual Center Center3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvArcSoh> InvArcSohs { get; set; }
        public virtual InvCnsTyp InvCnsTyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDoc> InvDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDoc> InvDocs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMstr> InvMstrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvOrdr> InvOrdrs { get; set; }
        public virtual InvRcptTyp InvRcptTyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRfDoc> InvRfDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRfDoc> InvRfDocs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvSerial> InvSerials { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual Unit Unit2 { get; set; }
        public virtual Unit Unit3 { get; set; }
        public virtual Unit Unit4 { get; set; }
        public virtual PartGrp PartGrp1 { get; set; }
        public virtual Unit Unit5 { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Unit Unit6 { get; set; }
        public virtual Unit Unit7 { get; set; }
        public virtual Unit Unit8 { get; set; }
        public virtual Unit Unit9 { get; set; }
    }
}
