//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaySysYr
    {
        public string RaySys { get; set; }
        public int Yr { get; set; }
        public string StartDate { get; set; }
        public string LastDate { get; set; }
        public Nullable<byte> IsClosed { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<byte> SupplementTerm { get; set; }
        public string SuppDate { get; set; }
        public string CurrDate { get; set; }
    
        public virtual RaySy RaySy { get; set; }
    }
}
