//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.InvAddDocInfs = new HashSet<InvAddDocInf>();
            this.InvAddDocInfHdrs = new HashSet<InvAddDocInfHdr>();
            this.InvArcSohs = new HashSet<InvArcSoh>();
            this.InvDocs = new HashSet<InvDoc>();
            this.InvDtlDatas = new HashSet<InvDtlData>();
            this.InvHdrDatas = new HashSet<InvHdrData>();
            this.InvMstrs = new HashSet<InvMstr>();
            this.InvRfDocs = new HashSet<InvRfDoc>();
            this.InvSeris = new HashSet<InvSeri>();
            this.InvSerials = new HashSet<InvSerial>();
            this.InvUserLvls = new HashSet<InvUserLvl>();
            this.PartGrps = new HashSet<PartGrp>();
            this.Store1 = new HashSet<Store>();
            this.Store11 = new HashSet<Store>();
        }
    
        public string StoreNo { get; set; }
        public string StoreDsc { get; set; }
        public string StoreLtnDsc { get; set; }
        public Nullable<int> WrkShp { get; set; }
        public Nullable<int> Center { get; set; }
        public string StoreMan { get; set; }
        public string StoreAddr { get; set; }
        public string PostCode { get; set; }
        public string PostBoxNo { get; set; }
        public string StoreTelNo { get; set; }
        public string FaxNo { get; set; }
        public Nullable<byte> PriceMet { get; set; }
        public Nullable<byte> RtrnBuyMet { get; set; }
        public Nullable<byte> RtrnStrReason { get; set; }
        public Nullable<byte> OpnPrcMet { get; set; }
        public Nullable<byte> OpnPrcMetShop { get; set; }
        public Nullable<short> StoreCountNo { get; set; }
        public Nullable<byte> AnbarGarType { get; set; }
        public Nullable<byte> StoreStatus { get; set; }
        public string ChkStartDate { get; set; }
        public string ChkEndDate { get; set; }
        public Nullable<byte> SerialAcc { get; set; }
        public Nullable<byte> Sorttag { get; set; }
        public Nullable<byte> Nexttagp { get; set; }
        public Nullable<byte> Gentagp { get; set; }
        public Nullable<decimal> ValueTag { get; set; }
        public Nullable<short> Countno { get; set; }
        public Nullable<byte> SerialTyp { get; set; }
        public Nullable<byte> Salable { get; set; }
        public Nullable<byte> IsMtrl { get; set; }
        public Nullable<byte> IsMchnPart { get; set; }
        public Nullable<byte> IsTools { get; set; }
        public Nullable<byte> IsAsset { get; set; }
        public Nullable<byte> IsMold { get; set; }
        public Nullable<byte> ISOfsTool { get; set; }
        public Nullable<byte> IsFccPart { get; set; }
        public Nullable<byte> IsConsTool { get; set; }
        public Nullable<byte> IsPrice { get; set; }
        public Nullable<byte> RelatedBuy { get; set; }
        public Nullable<byte> SerialInOrder { get; set; }
        public Nullable<byte> IsIssueWithRef { get; set; }
        public Nullable<byte> IsRcptWithRef { get; set; }
        public string MstrUpdDate { get; set; }
        public Nullable<byte> IsOwnerShip { get; set; }
        public string ShopCode { get; set; }
        public Nullable<byte> RelatedShop { get; set; }
        public Nullable<short> DayRcpt { get; set; }
        public Nullable<decimal> PerDiscount { get; set; }
        public Nullable<decimal> MaxDiscount { get; set; }
        public string DiscountUpdDate { get; set; }
        public Nullable<decimal> RcptDocDis { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<byte> TwoUnt { get; set; }
        public Nullable<byte> IsUnique { get; set; }
        public Nullable<byte> IsRtrnBuyWithRef { get; set; }
        public Nullable<byte> IsRtrnStrWithRef { get; set; }
        public string DestStore { get; set; }
        public Nullable<byte> RelatedAst { get; set; }
        public Nullable<byte> SerialFactor { get; set; }
        public Nullable<byte> IsShop { get; set; }
        public Nullable<byte> IsPrdPart { get; set; }
        public Nullable<byte> IsResQtySale { get; set; }
        public Nullable<byte> IsLaboratory { get; set; }
        public Nullable<byte> NotCnfrmLab { get; set; }
        public Nullable<byte> TestLab { get; set; }
        public Nullable<byte> PeriodTestLab { get; set; }
        public Nullable<byte> CnfrmLab { get; set; }
        public Nullable<int> LabReng { get; set; }
        public string LabOrderBy { get; set; }
        public string Mobile { get; set; }
        public string TypeId { get; set; }
        public string StateId { get; set; }
        public Nullable<byte> AndPartGrp { get; set; }
        public Nullable<byte> RelatedAmtBuy { get; set; }
        public Nullable<byte> StoreBinNo { get; set; }
        public Nullable<byte> IsWoFeed { get; set; }
        public Nullable<byte> IsMrpStk { get; set; }
        public Nullable<byte> IsMrpReq { get; set; }
        public Nullable<byte> ChkSohRqst { get; set; }
        public Nullable<byte> ChkSohIssue { get; set; }
        public Nullable<int> BinReng { get; set; }
        public Nullable<byte> Differcnt { get; set; }
        public Nullable<byte> IsStoreAmt { get; set; }
        public Nullable<byte> IsShowTowUntInRef { get; set; }
        public Nullable<byte> FiFoOrder { get; set; }
        public Nullable<byte> IsBatchSplit { get; set; }
        public Nullable<byte> PriceGroup { get; set; }
        public Nullable<decimal> ValueTagMain { get; set; }
        public Nullable<byte> IsSamePart { get; set; }
        public Nullable<byte> IsBisector { get; set; }
        public Nullable<byte> IsNotActvCnfrmLvl { get; set; }
        public Nullable<byte> IsBreakRow { get; set; }
        public Nullable<byte> IsResQtyPrd { get; set; }
        public Nullable<byte> SaveDoc { get; set; }
        public Nullable<byte> NotCheckOrderPoint { get; set; }
        public Nullable<byte> RelatedCrdt { get; set; }
        public Nullable<decimal> Diffper { get; set; }
        public Nullable<byte> IsStoreAnalysis { get; set; }
        public Nullable<byte> IsSendBuyCnfrm { get; set; }
        public Nullable<byte> IsEnableAmtForissue { get; set; }
        public Nullable<byte> IsWbsKAnalysis { get; set; }
        public Nullable<byte> IsChangeAfterRef { get; set; }
        public Nullable<byte> IsItemRcptWithRef { get; set; }
        public Nullable<byte> IsTempRcptWithRef { get; set; }
        public Nullable<byte> NotSerialPrice { get; set; }
        public Nullable<byte> IsCloseCount { get; set; }
        public Nullable<byte> IsPack { get; set; }
        public Nullable<byte> IsRealatedQc { get; set; }
        public Nullable<byte> IsTaxTollPrice { get; set; }
        public Nullable<byte> IsAllYrOrdrPoint { get; set; }
        public Nullable<int> TmpIssueReng { get; set; }
        public Nullable<byte> RcvWeight { get; set; }
        public Nullable<byte> IsOpenYear { get; set; }
        public Nullable<bool> ConnectToStoreSystem { get; set; }
        public Nullable<bool> UseSerial { get; set; }
        public Nullable<byte> UseSerialStep { get; set; }
        public Nullable<byte> IsRqstBuyWithRef { get; set; }
        public Nullable<byte> IsShowSohInRqst { get; set; }
        public Nullable<byte> IsPlaqueEqualSerial { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<byte> IsBetweenRcptWithRef { get; set; }
        public Nullable<byte> IsLabTools { get; set; }
    
        public virtual Center Center1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvAddDocInf> InvAddDocInfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvAddDocInfHdr> InvAddDocInfHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvArcSoh> InvArcSohs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDoc> InvDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvHdrData> InvHdrDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMstr> InvMstrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRfDoc> InvRfDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvSeri> InvSeris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvSerial> InvSerials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvUserLvl> InvUserLvls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartGrp> PartGrps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Store1 { get; set; }
        public virtual Store Store2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Store11 { get; set; }
        public virtual Store Store3 { get; set; }
    }
}
