//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.InvDocs = new HashSet<InvDoc>();
            this.InvDtlDatas = new HashSet<InvDtlData>();
            this.InvSerials = new HashSet<InvSerial>();
            this.ItemDatas = new HashSet<ItemData>();
            this.Supplier11 = new HashSet<Supplier>();
        }
    
        public string Supplier1 { get; set; }
        public string SupName { get; set; }
        public string SupLtnName { get; set; }
        public Nullable<short> Country { get; set; }
        public string SupPostCode { get; set; }
        public string Supaddr { get; set; }
        public string Supaddr2 { get; set; }
        public string SupTelNo { get; set; }
        public string SupTelNo2 { get; set; }
        public string SupFaxNo { get; set; }
        public string SupTlxNo { get; set; }
        public string SupEMail { get; set; }
        public string URL { get; set; }
        public string Mngr { get; set; }
        public string SaleMngr { get; set; }
        public string SupEcnmcNo { get; set; }
        public string SupNationCode { get; set; }
        public Nullable<int> Center { get; set; }
        public Nullable<decimal> SupDstnc { get; set; }
        public string SupFirstName { get; set; }
        public string SupLastName { get; set; }
        public string SupFthrName { get; set; }
        public string SupIdNo { get; set; }
        public string SupIdNoSrl { get; set; }
        public string SupIdNoIssue { get; set; }
        public Nullable<byte> IsProducer { get; set; }
        public Nullable<byte> SrcSup { get; set; }
        public Nullable<int> MultyMediaDoc { get; set; }
        public string MultyMediaDocX { get; set; }
        public Nullable<int> SaleRegionVCode { get; set; }
        public Nullable<int> County { get; set; }
        public Nullable<bool> IsAgent { get; set; }
        public Nullable<bool> isBuyOperator { get; set; }
        public Nullable<bool> IsFarmer { get; set; }
        public Nullable<bool> IsBusinessMan { get; set; }
        public Nullable<short> SupplierField { get; set; }
        public Nullable<int> Ratio { get; set; }
        public Nullable<byte> Zone { get; set; }
        public Nullable<byte> CityZone { get; set; }
        public Nullable<byte> RancherType { get; set; }
        public Nullable<byte> RancherGrp { get; set; }
        public Nullable<byte> Province { get; set; }
        public Nullable<byte> IsInGvrmntLongList { get; set; }
        public Nullable<byte> IsInCntrLongList { get; set; }
        public Nullable<byte> IsInOurLongList { get; set; }
        public Nullable<byte> Deactive { get; set; }
        public Nullable<int> CityTax { get; set; }
        public Nullable<byte> TaxMainId { get; set; }
        public Nullable<byte> TaxSubId { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
        public string POBox { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ContactPerson { get; set; }
        public Nullable<int> ExecutiveUnit { get; set; }
        public Nullable<int> ResponsibleUnit { get; set; }
        public string HoldingCompany { get; set; }
        public string VATExpireDate { get; set; }
        public Nullable<byte> CstmrStatus { get; set; }
    
        public virtual Center Center1 { get; set; }
        public virtual Center Center2 { get; set; }
        public virtual Center Center3 { get; set; }
        public virtual Center Center4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDoc> InvDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDtlData> InvDtlDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvSerial> InvSerials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemData> ItemDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Supplier11 { get; set; }
        public virtual Supplier Supplier2 { get; set; }
    }
}
