//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rayvarz.inv.assistant.service.Models.ray
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDomain
    {
        public string UserId { get; set; }
        public string RaySys { get; set; }
        public int Branch { get; set; }
        public string Func { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual Func Func1 { get; set; }
        public virtual RaySy RaySy { get; set; }
        public virtual UserId UserId1 { get; set; }
    }
}
